import { ReactNode, Suspense } from 'react';
import { Geist } from 'next/font/google';
import { cn } from '@/lib/utils';
import { SettingsProvider } from '@/providers/settings-provider';
import { TooltipsProvider } from '@/providers/tooltips-provider';
import { Toaster } from '@/components/ui/sonner';
import '@/css/styles.css';
import '@/components/keenicons/assets/styles.css';
import { Metadata } from 'next';
import { QueryProvider } from '@/providers/query-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import { SessionProvider } from '@/context/SessionContext';

const inter = Geist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Projitt',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className="h-full" suppressHydrationWarning>
      <body
        className={cn(
          'antialiased flex h-full text-base text-foreground bg-background',
          inter.className
        )}
      >
        <SessionProvider>
          <QueryProvider>
            <SettingsProvider>
              <ThemeProvider>
                <TooltipsProvider>
                  <Suspense>{children}</Suspense>
                  <Toaster />
                </TooltipsProvider>
              </ThemeProvider>
            </SettingsProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
